# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('customer', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(db_index=True, unique=True)),
                ('count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='0000', max_length=4)),
                ('card_number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(db_index=True, unique=True)),
                ('count', models.PositiveIntegerField(db_index=True, default=0)),
                ('minimum_to_notify', models.PositiveIntegerField(db_index=True, default=0)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.ATM')),
            ],
        ),
        migrations.AddField(
            model_name='addmoney',
            name='atm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.ATM'),
        ),
        migrations.AddField(
            model_name='addmoney',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
