# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='atm',
        ),
        migrations.RemoveField(
            model_name='money',
            name='count',
        ),
        migrations.RemoveField(
            model_name='money',
            name='minimum_to_notify',
        ),
    ]
