# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_auto_20170207_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='atm',
            name='minimum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atmmoney',
            name='atm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.ATM'),
        ),
        migrations.AddField(
            model_name='atmmoney',
            name='money',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.Money'),
        ),
    ]
