# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0003_auto_20170207_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoney',
            name='amount',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='addmoney',
            name='count',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='atmmoney',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
