# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atm', '0001_initial'),
        ('service', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('T', 'Transfer'), ('W', 'Withdraw'), ('D', 'Deposit')], db_index=True, max_length=1)),
                ('method', models.CharField(choices=[('C', 'Cheque'), ('A', 'ATM'), ('P', 'Periodic'), ('B', 'Bill'), ('H', 'Physical')], db_index=True, max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.ATM')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Bill')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Cheque')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='customer.Account')),
                ('periodic_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.PeriodicOrder')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='customer.Account')),
            ],
        ),
    ]
