# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='atm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atm.ATM'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Bill'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Cheque'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='customer.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='periodic_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.PeriodicOrder'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='customer.Account'),
        ),
    ]
