# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(db_index=True)),
                ('owner', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(db_index=True, default=0)),
                ('state', models.CharField(choices=[('N', 'Not Used'), ('WL', 'Waiting for Lawyer'), ('WA', 'Waiting for Auditor'), ('V', 'Verified'), ('DL', 'Declined by Lawyer'), ('DA', 'Declined by Auditor')], db_index=True, default='N', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ChequeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(db_index=True)),
                ('count', models.PositiveIntegerField(db_index=True)),
                ('state', models.CharField(choices=[('WL', 'Waiting for Lawyer'), ('WA', 'Waiting for Auditor'), ('V', 'Verified'), ('DL', 'Declined by Lawyer'), ('DA', 'Declined by Auditor'), ('D', 'Done')], db_index=True, default='WL', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(db_index=True)),
                ('amount', models.PositiveIntegerField(db_index=True)),
                ('state', models.CharField(choices=[('I', 'In Progress'), ('D', 'Done')], db_index=True, default='I', max_length=1)),
                ('type', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], db_index=True, default='D', max_length=1)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_periodic', to='customer.Account')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Loan')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_periodic', to='customer.Account')),
            ],
        ),
        migrations.AddField(
            model_name='cheque',
            name='cheque_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ChequeBook'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.BillType'),
        ),
    ]
